# WebIntel Configuration File
# This is the default configuration for WebIntel

# Google Gemini AI Configuration
gemini:
  # Your Gemini API key (can also be set via GEMINI_API_KEY environment variable)
  api_key: ""
  
  # Gemini model to use (gemini-2.0-flash is recommended for best performance)
  model_name: "gemini-2.0-flash"
  
  # Maximum tokens per AI request (1000-32000)
  max_tokens: 8192
  
  # Response creativity/randomness (0.0 = deterministic, 2.0 = very creative)
  temperature: 0.7
  
  # Nucleus sampling parameter (0.1-1.0, higher = more diverse)
  top_p: 0.9
  
  # Top-k sampling parameter (1-100, limits vocabulary)
  top_k: 40

# Web Scraping Configuration
scraping:
  # Maximum number of concurrent web requests (1-50)
  max_concurrent_requests: 10
  
  # Request timeout in seconds (5-120)
  request_timeout: 30
  
  # Number of retry attempts for failed requests (1-10)
  retry_attempts: 3
  
  # Delay between requests in seconds (0.1-5.0)
  delay_between_requests: 0.5
  
  # Maximum pages to scrape per website (1-20)
  max_pages_per_site: 5
  
  # Enable user agent rotation for better scraping success
  user_agent_rotation: true

# Output Configuration
output:
  # Default output format: rich, json, markdown, plain
  format: "rich"
  
  # Automatically save results to file
  save_to_file: false
  
  # Directory to save results
  output_directory: "./webintel_results"
  
  # Include source details in output
  include_sources: true
  
  # Maximum length of AI-generated summaries (500-5000)
  max_summary_length: 2000
